### ISSUE TITLE
Unnecessary use of hook?

### ISSUE THREAD

**Issue by wmdbMattes** [arnekolja/krbu_ce#3]
typo3/sysext/core/Documentation/Changelog/7.5/Feature-69459-ShowTt_contentPreviewInPageModuleViaFluid.rst

https://wiki.typo3.org/wiki/index.php?title=TYPO3.CMS/Releases/7.5/Feature#Feature:_.2369459_-_Show_tt_content_preview_in_page_module_via_Fluid

Isn't this, what the hook does?

**Comment by wouter90** [comment]
This is a new Feature that can be used to make previewing easier. The current usage works just fine. But for the extension purpose it would be nice to use the new Fluid rendering.

**Comment by arnekolja** [comment]
I think you are right. Demoing the preview hook should not be part of this extension, if it's not important and using Fluid directly is possible.
